"""Per-campaign ``CLAUDE.md`` generator (issue #131).

Claude Code auto-loads ``CLAUDE.md`` from each working / added directory
on every session, **once**. That makes it the right home for content that
is stable across calls within a campaign:

  * The campaign brief (research question, target system, observable
    metrics, controllable knobs).
  * The accumulated ``principles.json`` — the campaign's living knowledge
    base.
  * The most recent ``handoff.md`` — designer-to-executor context.

This module is a pure renderer: ``render_campaign_claude_md`` takes
inputs and returns a string; ``write_campaign_claude_md`` writes it to
disk. Regeneration after each iteration is deterministic Python — never
an LLM call.

The win this enables (full payoff lands when the prompt-template refactor
ships): each Nous LLM call no longer re-injects the campaign brief and
principles. Compounded with #122's ``cache_control: ephemeral`` on the
methodology system block, the bulk of static context is paid for once
per session, not once per turn.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from orchestrator.util import atomic_write


_HEADER = """# Nous Campaign Context

> This file is auto-generated by the orchestrator. **Do not hand-edit** —
> changes will be overwritten on the next iteration. The orchestrator
> updates the principles section after every iteration.
"""


def _format_principles(principles: list[dict] | None) -> str:
    """Render principles.json contents as a readable markdown section."""
    if not principles:
        return "_No principles accumulated yet._"
    lines: list[str] = []
    for p in principles:
        if not isinstance(p, dict):
            continue
        pid = p.get("id", "?")
        statement = p.get("statement") or p.get("description") or "(no statement)"
        category = p.get("category", "general")
        status = p.get("status", "active")
        if status != "active":
            continue
        lines.append(f"- **{pid}** [{category}]: {statement}")
    if not lines:
        return "_No active principles._"
    return "\n".join(lines)


def _format_target(target: dict) -> str:
    parts = [
        f"**{target.get('name', 'Unknown system')}**",
        target.get("description", ""),
    ]
    metrics = target.get("observable_metrics")
    if metrics:
        parts.append(f"\n**Observable metrics:** {', '.join(metrics)}")
    knobs = target.get("controllable_knobs")
    if knobs:
        parts.append(f"\n**Controllable knobs:** {', '.join(knobs)}")
    return "\n".join(p for p in parts if p)


def render_campaign_claude_md(
    *,
    campaign: dict,
    principles: list[dict] | None = None,
    last_handoff: str | None = None,
    iteration: int | None = None,
) -> str:
    """Build the CLAUDE.md content for one campaign.

    Sections (markdown headings the agent can navigate):
      1. Campaign brief — research_question, target_system summary.
      2. Active principles — formatted list from principles.json.
      3. Last handoff — designer→executor handoff from the most recent
         iteration that produced one (empty in iter 1).

    Returns the full markdown text. Caller is responsible for writing
    it to disk via ``write_campaign_claude_md``.
    """
    research_question = campaign.get("research_question", "(not set)")
    target = campaign.get("target_system", {})

    iter_line = f" (after iteration {iteration})" if iteration else ""

    sections = [
        _HEADER,
        "## Research Question\n",
        research_question.strip(),
        "",
        "## Target System\n",
        _format_target(target),
        "",
        f"## Active Principles{iter_line}\n",
        _format_principles(principles or []),
        "",
        "## Most Recent Handoff\n",
    ]
    if last_handoff and last_handoff.strip():
        sections.append(last_handoff.strip())
    else:
        sections.append("_First iteration — no prior handoff._")
    return "\n".join(sections) + "\n"


def write_campaign_claude_md(work_dir: Path, content: str) -> Path:
    """Atomically write CLAUDE.md to the campaign work-dir.

    Returns the absolute path to the file.
    """
    target = Path(work_dir) / "CLAUDE.md"
    atomic_write(target, content)
    return target.resolve()


def regenerate_from_disk(work_dir: Path, campaign: dict, iteration: int) -> Path:
    """Refresh CLAUDE.md after iteration N completes.

    Reads the current ``principles.json`` and ``handoff.md`` from
    ``work_dir`` and writes a freshly-rendered CLAUDE.md. Returns the
    absolute path written.
    """
    work_dir = Path(work_dir)
    principles: list[dict[str, Any]] = []
    p_path = work_dir / "principles.json"
    if p_path.exists():
        try:
            store = json.loads(p_path.read_text())
            principles = store.get("principles", [])
        except (json.JSONDecodeError, OSError):
            principles = []

    handoff_text: str | None = None
    h_path = work_dir / "handoff.md"
    if h_path.exists():
        try:
            handoff_text = h_path.read_text()
        except OSError:
            handoff_text = None

    content = render_campaign_claude_md(
        campaign=campaign,
        principles=principles,
        last_handoff=handoff_text,
        iteration=iteration,
    )
    return write_campaign_claude_md(work_dir, content)
